/**
 * OWASP LLM05:2025 — Improper Output Handling
 * XSS, SSRF, code injection via unvalidated LLM output
 */
const { v4: uuidv4 } = require('uuid');
async function run(target, config) {
  const findings = [];
  if (!target.output_sanitisation && !target.output_encoding) {
    findings.push({ id: uuidv4(), title: 'LLM output rendered without sanitisation', description: 'Model outputs are passed directly to downstream systems or rendered in UI without encoding or sanitisation. LLMs can generate XSS payloads, SQL fragments, or shell commands that execute in the downstream context.', severity: 'critical', confidence: 'probable', resource: target.name, evidence: 'output_sanitisation: false, output_encoding: false' });
  }
  if (target.code_execution_enabled && !target.output_validation_before_exec) {
    findings.push({ id: uuidv4(), title: 'LLM-generated code executed without pre-validation', description: 'The application executes code generated by the LLM without a validation or sandboxing step. A prompt injection could cause the model to generate malicious code that is then executed.', severity: 'critical', confidence: 'confirmed', resource: target.name, evidence: 'code_execution_enabled: true, output_validation_before_exec: false' });
  }
  return findings;
}
module.exports = { id: 'OWASP-LLM05', name: 'Improper Output Handling', run };
